/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expertsystem;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author selahattincincin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Panel
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        checkbox1 = new java.awt.Checkbox();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox_pb1siddet = new javax.swing.JCheckBox();
        jCheckBox_pb1hafif = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jCheckBox_TGYok = new javax.swing.JCheckBox();
        jCheckBox_TGVar = new javax.swing.JCheckBox();
        jLabel_pb1 = new javax.swing.JLabel();
        jComboBox_problem = new javax.swing.JComboBox<>();
        jLabel_tedaviGecmisi = new javax.swing.JLabel();
        jComboBox_fircAlis = new javax.swing.JComboBox<>();
        jLabel_cozumUret = new javax.swing.JLabel();
        btn_cozumUret = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cozumUret = new javax.swing.JTextArea();
        jLabel_fircalamaAliskanligi = new javax.swing.JLabel();
        jLabel_yas = new javax.swing.JLabel();
        jComboBox_yas = new javax.swing.JComboBox<>();
        jComboBox_kullandigi = new javax.swing.JComboBox<>();
        jLabel_ilac = new javax.swing.JLabel();
        jComboBox_tedaviGecmis = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 284, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        checkbox1.setLabel("checkbox1");

        jTextField1.setText("jTextField1");

        jCheckBox_pb1siddet.setText("Şiddetli");
        jCheckBox_pb1siddet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_pb1siddetActionPerformed(evt);
            }
        });

        jCheckBox_pb1hafif.setText("Hafif");

        jButton1.setText("Ekle");

        jCheckBox_TGYok.setText("Yok");

        jCheckBox_TGVar.setText("Var");
        jCheckBox_TGVar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_TGVarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dental Expert System");

        jLabel_pb1.setText("Problem :");

        jComboBox_problem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Çürük", "Diş Eti", "Diş Sallanması", "Diş Hassasiyeti", "Beyazlatma" }));
        jComboBox_problem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_problemActionPerformed(evt);
            }
        });

        jLabel_tedaviGecmisi.setText("Tedavi Geçmişi :");

        jComboBox_fircAlis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hiç", "Ara Sıra", "Normal", "Sık Sık" }));
        jComboBox_fircAlis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_fircAlisActionPerformed(evt);
            }
        });

        jLabel_cozumUret.setText("Çözüm Üret :");

        btn_cozumUret.setText("Çözüm Üret");
        btn_cozumUret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cozumUretActionPerformed(evt);
            }
        });

        cozumUret.setColumns(20);
        cozumUret.setRows(5);
        jScrollPane1.setViewportView(cozumUret);

        jLabel_fircalamaAliskanligi.setText("Fırçalama Alışkanlığı :");

        jLabel_yas.setText("Yaş :");

        jComboBox_yas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Çocuk", "Genç", "Orta", "Yaşlı" }));
        jComboBox_yas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_yasActionPerformed(evt);
            }
        });

        jComboBox_kullandigi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Var", "Yok" }));
        jComboBox_kullandigi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_kullandigiActionPerformed(evt);
            }
        });

        jLabel_ilac.setText("Kullandığı İlaçlar :");

        jComboBox_tedaviGecmis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Var", "Yok" }));
        jComboBox_tedaviGecmis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_tedaviGecmisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_pb1)
                            .addComponent(jComboBox_problem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_tedaviGecmisi)
                            .addComponent(jLabel_ilac)
                            .addComponent(jComboBox_kullandigi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_fircalamaAliskanligi)
                            .addComponent(jComboBox_fircAlis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_tedaviGecmis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox_yas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE)
                                .addComponent(jLabel_cozumUret)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_cozumUret))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_yas)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_pb1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_problem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_tedaviGecmisi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_tedaviGecmis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_ilac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_kullandigi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_fircalamaAliskanligi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_fircAlis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_yas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox_yas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_cozumUret)
                            .addComponent(jLabel_cozumUret))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_pb1siddetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_pb1siddetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_pb1siddetActionPerformed
    SolitionModel solitionModel;
    List<String> sonucList = new ArrayList<String>();
    String sonucum = null;
    private void btn_cozumUretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cozumUretActionPerformed
       solitionModel = new SolitionModel(jComboBox_problem.getSelectedIndex(),
                jComboBox_tedaviGecmis.getSelectedIndex(),
                jComboBox_kullandigi.getSelectedIndex(),
                jComboBox_fircAlis.getSelectedIndex(),
                jComboBox_yas.getSelectedIndex());
        
        Solition solition = new Solition();
        sonucList.add("Uzman Tavsiyesi : " + String.valueOf(solition.Solition(solitionModel)));
        
        for(int i = sonucList.size()-1; i<sonucList.size();i++){
            if(sonucum == null){
                sonucum = sonucList.get(i) + "\n";
            }
            else {
                sonucum = sonucum + sonucList.get(i) + "\n";
            }
                
            
        }
        cozumUret.setText(sonucum);
        
          
    }//GEN-LAST:event_btn_cozumUretActionPerformed

    private void jComboBox_problemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_problemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_problemActionPerformed

    private void jComboBox_fircAlisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_fircAlisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_fircAlisActionPerformed

    private void jCheckBox_TGVarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_TGVarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_TGVarActionPerformed

    private void jComboBox_yasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_yasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_yasActionPerformed

    private void jComboBox_kullandigiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_kullandigiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_kullandigiActionPerformed

    private void jComboBox_tedaviGecmisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_tedaviGecmisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_tedaviGecmisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cozumUret;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private java.awt.Checkbox checkbox1;
    private javax.swing.JTextArea cozumUret;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox_TGVar;
    private javax.swing.JCheckBox jCheckBox_TGYok;
    private javax.swing.JCheckBox jCheckBox_pb1hafif;
    private javax.swing.JCheckBox jCheckBox_pb1siddet;
    private javax.swing.JComboBox<String> jComboBox_fircAlis;
    private javax.swing.JComboBox<String> jComboBox_kullandigi;
    private javax.swing.JComboBox<String> jComboBox_problem;
    private javax.swing.JComboBox<String> jComboBox_tedaviGecmis;
    private javax.swing.JComboBox<String> jComboBox_yas;
    private javax.swing.JLabel jLabel_cozumUret;
    private javax.swing.JLabel jLabel_fircalamaAliskanligi;
    private javax.swing.JLabel jLabel_ilac;
    private javax.swing.JLabel jLabel_pb1;
    private javax.swing.JLabel jLabel_tedaviGecmisi;
    private javax.swing.JLabel jLabel_yas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
